app = "mi-proyecto-martin"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[deploy]
  # Ejecutar migraciones y collectstatic en cada despliegue
  release_command = "python manage.py migrate && python manage.py collectstatic --noinput"

[experimental]
  allowed_public_ports = [8080]
  auto_rollback = true
